# Generated by Django 3.2.3 on 2021-07-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=256)),
                ('translated_to_language', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('latname', models.EmailField(max_length=200)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('mobile_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(choices=[('new', 'New'), (' in-process', 'In-Process'), ('complete', 'Complete')])),
                ('translated_tex', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.project')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
    ]
